default: &default
  adapter: mysql2
  encoding: utf8
  port: 3306
  username: root
  password: "oomN8iy[z,"

development:
  <<: *default
  database: ohmpieng_development

test:
  <<: *default
  database: ohmpieng_test

production:
  <<: *default
  database: ohmpieng_production
