default: &default
  adapter: mysql2
  encoding: utf8
  pool: 10
  reaping_frequency: 60
  host: localhost
  database: application
  username: root
  password: "oomN8iy[z,"
  socket: /var/run/mysqld/mysqld.sock
  port: 3306

development:
  <<: *default
  database: application

test:
  <<: *default
  database: application

production:
  <<: *default
  database: application
