default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: application

test:
  <<: *default
  database: application_test

production:
  <<: *default
  database: application
  username: root
  password: ":vp.sh]n,f]d"
